"""Mesajlaşma özelliği eklendi

Revision ID: 5de9a34fced4
Revises: 8615ef23f57a
Create Date: 2025-07-29 18:57:41.922000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5de9a34fced4'
down_revision = '8615ef23f57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
