"""Kullanıcı rolleri eklendi

Revision ID: 87986f69b0dc
Revises: 8d46665ba29b
Create Date: 2025-07-29 17:25:52.252207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87986f69b0dc'
down_revision = '8d46665ba29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
