"""loglara timestamp eklendi

Revision ID: 9d326263ad44
Revises: c8348ed38d18
Create Date: 2025-07-29 18:04:25.776383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d326263ad44'
down_revision = 'c8348ed38d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('kullanici_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('kullanici_id')
        batch_op.drop_column('islem')
        batch_op.drop_column('zaman')
        batch_op.drop_column('detay')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detay', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('zaman', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('islem', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('kullanici_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('kullanici_log_ibfk_1'), 'user', ['kullanici_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('detail')
        batch_op.drop_column('action')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
