"""Loglama sistemi eklendi

Revision ID: c8348ed38d18
Revises: 87986f69b0dc
Create Date: 2025-07-29 17:49:46.698539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8348ed38d18'
down_revision = '87986f69b0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('islem', sa.String(length=100), nullable=True),
    sa.Column('zaman', sa.DateTime(), nullable=True),
    sa.Column('detay', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici_log')
    # ### end Alembic commands ###
